# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: jkrauze
author: Jędrzej Krauze
email: jedrzej.krauze@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        notebook
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jkrauze.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jkrauze

# Build settings
theme: huangyz0918/moving
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
  - publish.sh
  - publish_prefix.txt
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


moving:
  avatar_url: "https://avatars2.githubusercontent.com/u/17221843" # avatar in about page
  about_you: ...  # short description about you in about page
  date_format: "%m-%d" # date format of posts in home page

  # generate social links in about page.
  social_links:
    # twitter: 
    github:  jkrauze
    rss: RSS
    # dribbble: 
    # flickr:   
    # instagram: 
    linkedin: jedrzej-krauze
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

bucket:
  img:
    url: http://assets.ojoj.site
